[package]
name = "rustont-explorer"
version = "0.1.0"
authors = ["renshan <1005110700@qq.com>"]

[dependencies]
iron = "0.6.0"
router = "0.6.0"
persistent = "0.4.0"
serde = "1.0.55"
serde_derive = "1.0.55"
serde_json = "1.0.17"
serde_yaml = "0.7.4"
mysql = "*"
